services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: vue-spa
    hostname: alpine-node-22
    entrypoint: /bin/bash
    working_dir: /workspace
    volumes:
      - '.:/workspace'
    tty: true
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.vue-spa.rule=Host(`vue-spa.localhost`)"
      - "traefik.http.services.vue-spa.loadbalancer.server.port=${VITE_APP_PORT}"
    networks:
      - proxy

networks:
  proxy: # setup in separate container, example implementation: https://github.com/connorabbas/traefik-docker-compose/blob/master/docker-compose.yml
    name: "traefik_network"
    external: true
